#!/usr/bin/env bash
# Point nginx at Let's Encrypt certs when present, otherwise dev self-signed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"
SNIPPET="${SCRIPT_DIR}/snippets/ssl-certs.conf"
LE_ROOT="${SCRIPT_DIR}/letsencrypt"

TLS_DOMAIN="${TLS_DOMAIN:-}"
if [[ -z "${TLS_DOMAIN}" && -f "${ENV_FILE}" ]]; then
  TLS_DOMAIN="$(grep -E '^TLS_DOMAIN=' "${ENV_FILE}" | cut -d= -f2- | tr -d '\r' || true)"
fi

if [[ -n "${TLS_DOMAIN}" && -f "${LE_ROOT}/live/${TLS_DOMAIN}/fullchain.pem" && -f "${LE_ROOT}/live/${TLS_DOMAIN}/privkey.pem" ]]; then
  cat > "${SNIPPET}" <<EOF
# Let's Encrypt (${TLS_DOMAIN}) — generated by resolve-nginx-tls.sh
ssl_certificate     /etc/letsencrypt/live/${TLS_DOMAIN}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/${TLS_DOMAIN}/privkey.pem;
EOF
  echo "nginx TLS: using Let's Encrypt cert for ${TLS_DOMAIN}"
else
  cat > "${SNIPPET}" <<'EOF'
# Dev self-signed — generated by resolve-nginx-tls.sh
ssl_certificate     /etc/nginx/certs/dev.crt;
ssl_certificate_key /etc/nginx/certs/dev.key;
EOF
  echo "nginx TLS: using dev self-signed cert (set TLS_DOMAIN + make tls-cert for production)"
fi
