/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120294-g25e710c61e-20250717"
#endif /* AVUTIL_FFVERSION_H */
